// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TraplineEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Type        uint32
	Daddr       uint32
	OpenFlags   uint32
	Dport       uint16
	Sport       uint16
	Comm        [16]int8
	Pcomm       [16]int8
	Filename    [256]int8
	Argv        [128]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TraplineMapConnectSockets      = "connect_sockets"
	TraplineMapEvents              = "events"
	TraplineProgKpTcpV4Connect     = "kp_tcp_v4_connect"
	TraplineProgKrpTcpV4Connect    = "krp_tcp_v4_connect"
	TraplineProgTpSchedProcessExec = "tp_sched_process_exec"
	TraplineProgTpSysEnterOpenat   = "tp_sys_enter_openat"
	TraplineVarUnusedEvent         = "unused_event"
)

// LoadTrapline returns the embedded CollectionSpec for Trapline.
func LoadTrapline() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraplineBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Trapline: %w", err)
	}

	return spec, err
}

// LoadTraplineObjects loads Trapline and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TraplineObjects
//	*TraplinePrograms
//	*TraplineMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTraplineObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTrapline()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TraplineSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraplineSpecs struct {
	TraplineProgramSpecs
	TraplineMapSpecs
	TraplineVariableSpecs
}

// TraplineProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraplineProgramSpecs struct {
	KpTcpV4Connect     *ebpf.ProgramSpec `ebpf:"kp_tcp_v4_connect"`
	KrpTcpV4Connect    *ebpf.ProgramSpec `ebpf:"krp_tcp_v4_connect"`
	TpSchedProcessExec *ebpf.ProgramSpec `ebpf:"tp_sched_process_exec"`
	TpSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_openat"`
}

// TraplineMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraplineMapSpecs struct {
	ConnectSockets *ebpf.MapSpec `ebpf:"connect_sockets"`
	Events         *ebpf.MapSpec `ebpf:"events"`
}

// TraplineVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TraplineVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// TraplineObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTraplineObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraplineObjects struct {
	TraplinePrograms
	TraplineMaps
	TraplineVariables
}

func (o *TraplineObjects) Close() error {
	return _TraplineClose(
		&o.TraplinePrograms,
		&o.TraplineMaps,
	)
}

// TraplineMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTraplineObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraplineMaps struct {
	ConnectSockets *ebpf.Map `ebpf:"connect_sockets"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *TraplineMaps) Close() error {
	return _TraplineClose(
		m.ConnectSockets,
		m.Events,
	)
}

// TraplineVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTraplineObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraplineVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// TraplinePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTraplineObjects or ebpf.CollectionSpec.LoadAndAssign.
type TraplinePrograms struct {
	KpTcpV4Connect     *ebpf.Program `ebpf:"kp_tcp_v4_connect"`
	KrpTcpV4Connect    *ebpf.Program `ebpf:"krp_tcp_v4_connect"`
	TpSchedProcessExec *ebpf.Program `ebpf:"tp_sched_process_exec"`
	TpSysEnterOpenat   *ebpf.Program `ebpf:"tp_sys_enter_openat"`
}

func (p *TraplinePrograms) Close() error {
	return _TraplineClose(
		p.KpTcpV4Connect,
		p.KrpTcpV4Connect,
		p.TpSchedProcessExec,
		p.TpSysEnterOpenat,
	)
}

func _TraplineClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trapline_x86_bpfel.o
var _TraplineBytes []byte
